### ISSUE TITLE
Execute the msb command line utility that is generated from the Gradle Application plugin

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#77]
As a developer
I want to TITLE
So that I can quickly deploy the msb command line utility.  

    gradle :core:distZip

Want the utility to be called "msb" not core.

**Comment by sastafford** [comment]
@rjrudin Having trouble running a JobConfig with the application scripts which are generated.  

e:\temp\core\core\bin>core.bat --config DeleteDocumentsConfig.class --collections test --jrHost oscar --jrPort 8200 --jrUsername admin --jrPassword admin

Exception in thread "main" java.lang.RuntimeException: Unable to register configuration for class: DeleteDocumentsConfig.class
        at com.marklogic.spring.batch.Main.registerConfigurationsFromOptions(Main.java:160)
        at com.marklogic.spring.batch.Main.buildApplicationContext(Main.java:132)
        at com.marklogic.spring.batch.Main.runJob(Main.java:84)
        at com.marklogic.spring.batch.Main.main(Main.java:43)
Caused by: java.lang.ClassNotFoundException: DeleteDocumentsConfig.class
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.marklogic.spring.batch.Main.registerConfigurationsFromOptions(Main.java:158)
        ... 3 more
